# Generated by Django 5.0.1 on 2024-01-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excel_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=15)),
                ('Industry_aggregation_NZSIOC', models.CharField(max_length=50)),
                ('Industry_code_NZSIOC', models.CharField(max_length=50)),
                ('Industry_name_NZSIOC', models.CharField(max_length=50)),
                ('Units', models.CharField(max_length=50)),
                ('Variable_code', models.CharField(max_length=50)),
                ('Variable_name', models.CharField(max_length=50)),
                ('Variable_category', models.CharField(max_length=50)),
                ('Value', models.FloatField()),
                ('Industry_code_ANZSIC06', models.CharField(max_length=255)),
            ],
        ),
    ]
